name: Selenium Ide CI

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main             
         
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set execute permissions for Selenium Manager
        run: chmod +x ./SeleniumIDE/bin/Debug/net6.0/selenium-manager/linux/selenium-manager
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
          
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --verbosity normal